# Generated by Django 4.2.4 on 2023-08-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
