# Generated by Django 4.2.4 on 2023-08-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
