# Generated by Django 4.2.4 on 2023-08-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
