# Generated by Django 4.2.4 on 2023-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_student_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
