# Generated by Django 4.2.4 on 2023-08-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_alter_people_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
